### ISSUE TITLE
Android 4.2 support ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#10]
Could you add support for Android 4.2 ?

p.s. Thanks for the proxy.

**Comment by krlvm** [comment]
Previously, PowerTunnel supported Android Jelly Bean (4.1) and higher, but I had to bump the minimum OS version to Lollipop (5.1) due to issues with compiling of dnsjava. I can try to compile a binary you need, but can guarantee nothing. Consider switching to [version v1.0](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.0).

**Comment by krlvm** [comment]
Seems I was not right, I was able to compile APK with minimum API 16.

I've built a [version](https://github.com/krlvm/PowerTunnel-Android/files/4594798/PowerTunnel-v1.4-compat.zip) based on the latest version PowerTunnel (v1.4), it should work with your device. Can't test it, because I don't have an Android 4.2 device, please, write a feedback.

**Comment by krlvm** [comment]
Вы проверили эту версию на работоспособность? Если все работает, то я включу поддержку старых версий Android в основную ветку разработки и следующая версия будет с ними совместима.
Вы будете автоматически обновлены до нее со сборки, прикрепленной в предыдущем моем сообщении.

**Comment by Baltazar500** [comment]
Ещё не успел. Просто смарт с 4.2 был недоступен. Скачал. Буду тестировать

**Comment by Baltazar500** [comment]
Работает :) Разве что иконка в панели уведомлений полностью слилась с панелью, а так всё ОК.

**Comment by krlvm** [comment]
Спасибо.
Следующая версия PowerTunnel будет иметь поддержку устаревших версий Android - пока вы можете использовать эту сборку, а как только выйдет новая версия, вам придет уведомление.

**Comment by krlvm** [comment]
Поддержка Android 4.2 более невозможна по причине миграции на обновленный LittleProxy, [PowerTunnel for Android v1.5.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5.1) - последняя версия, которая поддерживает данную ОС, оповещения о выходе новых версий на неподдерживаемые версии ОС приходить не будут.

Минимальная версия Android начиная с PowerTunnel for Android v1.6 - Android KitKat 4.4.

**Comment by Baltazar500** [comment]
Обратил внимание, что не обновился на 4.2.2 до 1.5.1, произвёл апдейт, всё равно выше по идее не должно работать. Потом снова ткнул обновить. Вылезло предложение обновиться до 1.8.1. Ну я и обновился. И вроде всё работает. Потом залез в данное issue и увидел зачёркнутый пост о прекращении поддержки 4.2.2. Т.е. PowerTunnel пока продолжает  свою работу на 4.2.2 ?

**Comment by krlvm** [comment]
Да, я отказался от миграции на новый LittleProxy из-за его нестабильности, поэтому поддержка 4.4 продолжается, а обновление на 1.5.1 необходимо для поиска обновлений с проверкой минимальной версии Android.
