### ISSUE TITLE
How about a firewall system?

### ISSUE THREAD

**Issue by MasterKraid** [krlvm/PowerTunnel-Android#117]
Many people have used glasswire right? 
This is not a promotion of sorts.
Glasswire let users select what applications can send and receive data, that's the gist of right? 
Now I can't use glasswire and powertunnel at the same time. And if powertunnel dev implements a similar firewall like addon for the pc and Android ver. It would be a win win for all, cuz like a lot of people will now use power tunnel, cuz it would be like a new alternative to a paid and not Open-source Glasswire and people trust open source project and tend to lean towards free software more often than paid. 
If above mentioned addon is already present and I can't see, can someone help me find it or something similar?

That's about it, thanks for reading.
When I learn stuff I will try to make an add on myself, if my words aren't heard.
Am sorry if I wasn't able to express my view properly am just a person who learned half of his English from the internet lol

**Comment by krlvm** [comment]
Unfortunately, this is impossible to achieve on desktop, because proxy server can't determine the application that sent the request.

On Android, some additional data, including application which tries to access the Internet, is passed by OS when PowerTunnel is in VPN mode, and it should be enough to implement this kind of filter, but this is out of scope of the project.

If you need to forbid access to some URLs, you can install [Firewall](https://github.com/krlvm/PowerTunnel-Firewall) plugin.
You may also be interested in [NetGuard](https://github.com/M66B/NetGuard), which powers PowerTunnel's VPN service.
