### ISSUE TITLE
Proxy Server + authentication

### ISSUE THREAD

**Issue by chr0sy** [krlvm/PowerTunnel-Android#23]
Hi. Great app. One question, can I use it with a USA proxy server? Meaning can I use it to connect to a paid-premium proxy server so i can unblock Netflix and other websites? Also does this support proxy authentication (username:password)

**Comment by krlvm** [comment]
1) If you have a proxy server located in country that doesn't restrict access to a resource you want connect to, if I understand correctly, you don't have to use PowerTunnel I think.
2) PowerTunnel proxy server doesn't support authentication, just left username/password fields empty.

**Comment by chr0sy** [comment]
Hi, the idea is that I want to use your app or this app:
https://github.com/raise-isayan/TunProxy to be able to enter a proxy
ip:port:username:password and connect. Are you available for hire? Neither
TunProxy accepts authentication and i need someone to do that for me.

**Comment by krlvm** [comment]
I am exploring the possibility of realizing this, I think I can write back within a couple of hours.

**Comment by chr0sy** [comment]
Thank you. The idea is that Android supports it. Just go to your Wifi
settings and see that you can set a username and password in proxy manual
settings. I have already customized this app to my needs and only need
this.

Do you have any IM to talk?

**Comment by krlvm** [comment]
You can find my in Telegram Messenger by my nickname.

**Comment by megapro17** [comment]
Any news on this?

**Comment by krlvm** [comment]
> Any news on this?

It is possible, but I do not think this functionality is needed in PowerTunnel.

**Comment by megapro17** [comment]
> > Any news on this?
> 
> It is possible, but I do not think this functionality is needed in PowerTunnel.

Is there any way to use proxy/vpn with powertunnel?

**Comment by krlvm** [comment]
> > > Any news on this?
> > 
> > 
> > It is possible, but I do not think this functionality is needed in PowerTunnel.
> 
> Is there any way to use proxy/vpn with powertunnel?

PowerTunnel is a proxy itself, it is not an app to connect to a proxy.

**Comment by megapro17** [comment]
I know, I just want to use Powertunnel with shadowsocks, it is possible?

**Comment by megapro17** [comment]
А, короче, мне всего один трюк нужен, пробел после GET, это можно добавить в shadowsocks без особых усилий? Не подскажете в какой файл?

**Comment by krlvm** [comment]
К сожалению, я не специалист по shadowsocks, можно попробовать проксировать запросы внутри PowerTunnel (например, указать прокси внутри нужного приложения, включить PowerTunnel, и тогда трафик уже пойдет внутри VPN соединения).

**Comment by DRSDavidSoft** [comment]
@krlvm This feature is super useful in three scenarios:

1. The internet access is only available via three upstream proxy (e.g. in corporate or university settings)
2. Some websites can be bypassed via PT, while officers explicitly need to go through an upstream proxy
3. Using PT's excellent implementation of the TunProxy library to force using HTTP proxy for apps that don't support it, or when using mobile data.

It would be awesome if PT could use an upstream proxy, especially if SSL tunnel (**HTTPS** proxy) could also be utilized. 

Android doesn't natively support HTTP **S** proxy, only plain HTTP, which is not encrypted.

**Comment by krlvm** [comment]
> @krlvm This feature is super useful in three scenarios:
> 
> 1. The internet access is only available via three upstream proxy (e.g. in corporate or university settings)
> 2. Some websites can be bypassed via PT, while officers explicitly need to go through an upstream proxy
> 3. Using PT's excellent implementation of the TunProxy library to force using HTTP proxy for apps that don't support it, or when using mobile data.
> 
> It would be awesome if PT could use an upstream proxy, especially if SSL tunnel (**HTTPS** proxy) could also be utilized.
> 
> Android doesn't natively support HTTP **S** proxy, only plain HTTP, which is not encrypted.

Sorry for misunderstanding, did I understand correctly that you need the ability to forward the connection through PowerTunnel to the proxy server which is required to access the Internet by your ISP?

**Comment by DRSDavidSoft** [comment]
@krlvm Yes, that is one of the possible use cases:

```
[android-device]  ---->  [PowerTunnel]  ---->  Upstream Proxy
```

This ability would be awesome to have for multiple reasons that I outlined, one of which being that Internet is only available through the upstream proxy server.

**Comment by krlvm** [comment]
> @krlvm Yes, that is one of the possible use cases:
> 
> ```
> [android-device]  ---->  [PowerTunnel]  ---->  Upstream Proxy
> ```
> 
> This ability would be awesome to have for multiple reasons that I outlined, one of which being that Internet is only available through the upstream proxy server.

I've started to work on this request a few weeks ago, but was very busy, I think I will release a new version by the end of month.
For what purpose are you going to use PowerTunnel? If only for connecting to a proxy server, without DPI bypass, then this is not very effective (VPN -> PowerTunnel Proxy -> Your proxy -> Internet), for this it is better to use pure TunProxy (VPN -> Your proxy -> Internet). Or do you need authorization support?

**Comment by DRSDavidSoft** [comment]
@krlvm Awesome, I hope to see this feature released soon (hopefully, on both Windows and Android).

No worries about being busy, when this feature arrives it would a welcome one.



As on the purpose of using PowerTunnel with an upstream proxy, the problem with using only `TunProxy` is that it doesn't have the DNS-over-HTTPS feature and a nice GUI with all the options that you've implemented in PowerTunnel (e.g. quick connect button, while a solution like [VPN Client Pro](https://play.google.com/store/apps/details?id=it.colucciweb.vpnclientpro&hl=en&gl=US) has that button).  Plus, I don't have to use [Intra](https://play.google.com/store/apps/details?id=app.intra&hl=en&gl=US) alongside the actual `TunProxy` to both use a proxy and encrypt the DNS (you cannot use multiple VPN connections in Android).

The authorization support is also a nice feature, but what I really think is useful if you could implement it, would be **HTTPS** proxy support (proxy over SSL); e.q. using [`https_proxy`](http://www.squid-cache.org/Doc/config/https_port/) directive in Squid proxy server.  That way, the government cannot inspect the ongoing traffic, as it's always being encrypted.  This is what the closed-source [UPX Browser](https://play.google.com/store/apps/details?id=net.upx.proxy.browser&hl=en&gl=US) is using internally.  I have also asked for this on a similar project called [DPITunnel](https://github.com/zhenyolka/DPITunnel/issues/8), which would be an awesome functionality to have.

Additionally, if you could implement conditional forwarding using a list (kind of like how the government domains list exists), then we can apply DPI obfuscation methods (like `Host` header modifications or SNI modifications) on domains that can be bypassed that way;  then forward everything else to the proxy server.  I can confirm that _some_ domains work with PowerTunnel's method, but several others need to be forwarded to the proxy server.

P.S. Alternatively, instead of **HTTPS** proxy, an HTTP proxy over [Chisel](https://github.com/jpillora/chisel/issues/86) can be used, which is awesome since it can work over Cloudflare and similar services.  There's already [socks support for chisel](https://github.com/kawaiiDango/chiselsocksdroid) -- but I believe the HTTP proxy is superior in this case.

Sorry for the long comment!
