### ISSUE TITLE
Live DNS logs in the app

### ISSUE THREAD

**Issue by Scripterr** [krlvm/PowerTunnel-Android#40]
It would be nice to see live DNS log in the app and connection going in and out through power tunnel.

**Comment by krlvm** [comment]
Why do you need this?

**Comment by Scripterr** [comment]
I need to see which domains are connecting from my phone and domains blocked or rejected (I'm using adblocking DNS server) if its possible to know, it would be nice to also get on device adblocking without depending on server level blocking but it would be maybe too much of work.

**Comment by krlvm** [comment]
I had this in my plans, but at the moment I have abandoned it, because it will lead to the need to maintain lists of sites with ads, I also cannot say for sure what effect it will have on performance, although it is quite simple to implement. I have drafts that implement DNS and proxy level filtering.
I know there is a cool and open-source ad-blocking project [Blokada](https://github.com/blokadaorg/blokada), which filters the traffic on your device, IIRC it can be configured to work with PowerTunnel: disable VPN mode in PowerTunnel and setup Blokada to use proxy server 127.0.0.1:8085.

**Comment by DRSDavidSoft** [comment]
I'm fine with a simple DNS logging for now, whenever you have time.

**Comment by krlvm** [comment]
I think that this probably goes out of the scope of the project.
