### ISSUE TITLE
Where and how would I log the returned HTML?

### ISSUE THREAD

**Issue by timmccabe** [krlvm/PowerTunnel-Android#47]
I am trying to see if I can, inside the PowerTunnel app, log the HTML that is returned.

While PowerTunnel is running in an Android virtual device via Android Studio, if I open Chrome browser and go to a URL, where or how could I Log.d() the HTML that has been returned for the webpage? Which function would be the best place to get the HTML? And how would I obtain it? Or, is it even available at all? If it is not available, is there some way to obtain the title of the webpage? Or, at minimum, the full URL (not just the domain)?

This is not a bug with your software. My goal right now is to learn more about how proxies work in Java, particularly in Android devices... and I'm having a great deal of difficulty understanding it all.

Thank you for any assistance or suggestions you can provide! Or even a good tutorial you can point me to!

**Comment by krlvm** [comment]
Hello.

You can't read the HTML of the loaded webpage (and plain text too), because in 99% of the time you download it over HTTP**S** - all traffic is encrypted (including the title), and you can't do anything about it other that MITM-ing the session and re-signing each HTTPS request with your own certificate, so you will be able to decrypt it later.

These precautions were put in place just to ensure that no one could interfere with the connection. So, if you want to monitor a session, even MITM hardly can help, because it breaks many sites - for example, DailyMotion validates the certificate to protect users from MITM attacks.

I highly recommend you to read more about HTTP and HTTPS before proceeding with proxies, because learning how HTTP proxies work is pretty hard without basic knowledge about how this protocols work.
_HTTP protocol and proxying is about more than just HTML._

If you understand what you are talking about and you need to read exactly HTTP, in current PowerTunnel implementation you have two ways to do that: either on LittleProxy (proxy, higher), or on TunProxy (VPN traffic interceptor, lower) level. To read content of HTTP requests on proxy level you just need to wait (add some rules to filtering, you can read more in LittleProxy documentation) until the entire request (`FullHttpRequest`) is buffered; to do this on TunProxy level you need to do the same, but all buffering work is on you. 

I also don't this PowerTunnel (especially on Android - you'd better do this on PC) is suitable for learning proxies because it very complex and serves for a different purpose, you may be interested in setting up a simple Node.js proxy that can be debugged easily.

Have a good day.
