### ISSUE TITLE
WIFI routers support...

### ISSUE THREAD

**Issue by rajsharma91** [krlvm/PowerTunnel-Android#69]
Yes, i know that most of the routers already have a VPN connection feature.

I have a 40 Mbps broadband connection which gives me around 20 to 25 Mbps speed in VPN (Free & Paid).

But i need speed and a stable connection. Like PowerTunnel.

Can we configure WIFI router for PowerTunnel like OpenVpn configuration file now or in near future?

**Comment by krlvm** [comment]
PowerTunnel is not a VPN actually, it is a proxy server and the Android version wraps it into a VPN connection.

So, you can route all your traffic directly via proxy server without VPN. But to run PowerTunnel on router it should support Java, so you need OpenWrt (^). Running it on different device in your network would not help because traffic route will loop (Device -> Router -> Device -> Router -> ...).

(^) If you have OpenWrt on your router, you can use [zapret](https://github.com/bol-van/zapret).
