### ISSUE TITLE
What is the difference between a proxy and a VPN?

### ISSUE THREAD

**Issue by kimpig** [krlvm/PowerTunnel-Android#72]
Hello, thank you for developing the app. This may be a bit of a weird question, but I have one question. I usually use it with Adguard in proxy mode and some sites cannot be accessed in proxy mode. However, if I use VPN mode instead of proxy mode, access to those sites will be smooth. What's the difference between these two methods?

**Comment by krlvm** [comment]
PowerTunnel itself is a proxy server, but Android version uses special library which wraps it into VPN Service. The only key difference is that when PowerTunnel is running in proxy mode, you need to configure all applications so that they are proxied through PowerTunnel (and manually disable these settings every time PowerTunnel is turned off and not needed, this cannot be automated without root). Setting up a system-wide proxy server on Windows or Linux is much easier than it is on Android.

At the same time, when a VPN is enabled on an Android device, all traffic from applications is proxied through it by default - there is no need to configure applications or turn off the system-wide proxy server every time.

Why you can't unblock some websites with AdGuard? Maybe it normalizes some traffic modified by PowerTunnel. You can try to do the opposite: run PowerTunnel in VPN mode, and AdGuard in proxy mode, then configure it in PowerTunnel and remember to add AdGuard to the list of excluded applications (now it slows down a little, but I'll fix it in the next release).
