### ISSUE TITLE
Option to send HTTPS hostname instead of CONNECT to ip address

### ISSUE THREAD

**Issue by DRSDavidSoft** [krlvm/PowerTunnel-Android#73]
Hey there,

Currently, when using the **upstream proxy** with no SNI tricks checked, PowerTunnel performs a `CONNECT` request to `<ip>:<port>`.  This works great for local upstream proxy servers (e.g. Adguard, Squid, etc)

However, some ISPs or other firewalls, require "named" HTTP Connect requests, e.g. `CONNECT example.com:443` instead of `CONNECT 93.184.216.34:443`.  Otherwise, the request would fail with a 504 error.

Therefore, I was wondering if you could add a new option in order to _optionally_ set the CONNECT host to the correct request hostname, instead of resolving it using the specified DNS server.

One benefit of such option is to allow custom domains that work locally to go through (e.g. `.local`, etc).

Would it be possible to add such option? (example: [x] ``` Send HTTPS hostname to upstream proxy ``` <sup>(instead of resolving locally)</sup>)

I would appreciate it if you could implement this feature, so we can continue to use **PowerTunnel**'s awesome features in these conditions! 😄 

Thank you

**Comment by krlvm** [comment]
Actually, that's how it _should_ work, but in VPN mode it sends IP address instead of hostname because the internal proxy server receives packets with encypted headers - they are encrypted before being sent to the VPN server. In proxy mode, everything works as expected.

This thing is also preventing me from adding blacklist support to filter only blocked websites and ad blocking functionality.

I have some thoughts how to make it working properly in VPN mode and resolve these two issues: the hostname in HTTPS packets is in SNI, which is parsed by tun2http and we have it here (if it was not resolved before): 
https://github.com/krlvm/PowerTunnel-Android/blob/07189269a1e37b7aad2492eaeb9ac97bdf700fb0/app/src/main/cpp/tcp.c#L530
Then packet's hostname changes to IP Address
https://github.com/krlvm/PowerTunnel-Android/blob/07189269a1e37b7aad2492eaeb9ac97bdf700fb0/app/src/main/cpp/tcp.c#L736
https://github.com/krlvm/PowerTunnel-Android/blob/07189269a1e37b7aad2492eaeb9ac97bdf700fb0/app/src/main/cpp/tcp.c#L739
If my assumption is correct, then in the case of an active upstream proxy, it is possible not to resolve the hostname in tun2http so that it is transmitted to the local proxy server, but again, I'm not sure that the hostname hasn't been resolved before packet got to tun2http. In this case, you can either substitute the SNI hostname into the packet, or add an unencrypted header with the hostname and then remove it at the local proxy level, but I'm not sure if this is a good solution.

**Comment by DRSDavidSoft** [comment]
Curious, I actually thought that PowerTunnel behaved like this intentionally.  Unfortunately, the Proxy mode cannot be used in some scenarios, while `tun2http` can (especially on non-rooted phones for family and friends).

Also, it makes sense that in Proxy mode the hostname is known, while in the VPN mode it isn't.

However, the first idea I got this was to parse the SNI field from the TLS request, which you've already figured out:

> the hostname in HTTPS packets is in SNI, which is parsed by tun2http and we have it here (if it was not resolved before)

The only issue I could see with this is when the SNI theoretically wouldn't match the actual HTTP hostname (which is not a valid case for most web servers - thus is safe to assume it'll work without problems).

The other issue is passing along custom domains that are not resolved by the DNS (e.g. `.local` and/or `.onion` domains for Tor).

This is because the IP address of the destination is resolved, before routing the actual request over PowerTunnel (which breaks custom domains, as they cannot be resolved by the DNS server.)

Proxifier solves this issue on Windows by allocating a special loopback IP address (e.g. `127.8.0.1`) that is reserved for domains that haven't been resolved yet, which also includes domains that cannot be resolved by the DNS server.

If the connection can be relayed, it simulated a TCP connection open, otherwise, it'll simulate a "connection refused" message.

Although I believe this part of the process should be implemented in `tun2http`, and not PowerTunnel -- which is sad because I haven't seen any development on that project recently.

> In this case, you can either substitute the SNI hostname into the packet or add an unencrypted header with the hostname and then remove it at the local proxy level

I'm not sure we would need to modify the content of the TLS packet itself, only the `HTTP CONNECT` layer should be modified to send the correct hostname, instead of the IP address.

I think it wouldn't matter if `tun2http` resolves the hostname or not, when the packet is received by PowerTunnel, you can parse the SNI and place it in the `HTTP CONNECT` hostname.

It wouldn't be a bad idea to do this at the proxy level -- remember, `CONNECT` is ONLY specific to the proxy level itself, and it wouldn't be relevant if we weren't using an upstream proxy anyway - as the connections would go through directly.

Also also, since in some cases the root CA is already installed, we can ignore the encryption layer altogether and extract the _actual_ HTTP `Host` header from the plain-text HTTP layer, either by deciphering the outgoing connection, or matching it internally. Of course, that's just a thought, and obviously, it wouldn't work when the root CA is not installed.

Thanks for taking time and putting your thought into this, this is a valuable addition to have.

**Comment by krlvm** [comment]
I will try to resolve this in the soon and start refactor the code, by the way, it turned out that in fact tun2http/TunProxy is [NetGuard](https://github.com/raise-isayan/TunProxy/issues/15) actually (ToDo: update copyrights).

**Comment by krlvm** [comment]
Hello and sorry for late response, there's two working solutions:
1) enabling any DoH server, so `lookup_hostname` will do nothing
2) commenting out line tcp.c#736, so it will not resolve hostname and will leave it to your upstream proxy

If you are using an upstream proxy for a specific non-proxying reason, you might be interested in the PowerTunnel v2.x Plugins API.

I'm currently developing the next version which will include an option for (2) without setting DoH server along with many other changes, so if you need (2) right now and migration to 2.x would be inconvenient for you, let me know and I will release v1.9.2 right now.

**Comment by krlvm** [comment]
This is APK containing solution (2) at [0acc56b](https://github.com/krlvm/PowerTunnel-Android/commit/0acc56bcfea37f94adb17b8e9075ee52da25bb18):
[PowerTunnel-v1.9.2-dev.zip](https://github.com/krlvm/PowerTunnel-Android/files/7014013/PowerTunnel-v1.9.2-dev.zip)

**Comment by DRSDavidSoft** [comment]
@krlvm Thank you for your time and implementing this! I was away for a couple of days myself.

I'm going to try the changes and will report right away!

**Comment by krlvm** [comment]
Finally available in [v2.0 stable](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0).
