### ISSUE TITLE
Fresh pull fails to build - duplicate function declaration

### ISSUE THREAD

**Issue by subworx** [krlvm/PowerTunnel-Android#90]
Using Android Studio Arctic Fox 2020.03.1 P2

Open Project from VCS, clone the project from master, Build -> Make Project.

```
Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.D8MainDexListTask$MainDexListWorkerAction
   > Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type io.netty.handler.codec.http.HttpMethod is defined multiple times: C:\Users\Username\.gradle\caches\transforms-2\files-2.1\e92e8fc23da913407fc711240bd6a445\jetified-littleproxy-1.1.2-littleproxy-shade.jar:io/netty/handler/codec/http/HttpMethod.class, C:\Users\Username\AndroidStudioProjects\PowerTunnel-Android\app\build\intermediates\javac\debug\classes\io\netty\handler\codec\http\HttpMethod.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

It worked once before, had to re-download source as I messed up badly, wouldn't work again afterwards with this error. 
No idea why, as I am not sure if I changed something in the IDE to cause it stop working except changing Gradle generate Job list setting.

**Comment by krlvm** [comment]
It's a bit complicated to build the app because it overrides some dependency classes - that's OK with Java Gradle build (like in PowerTunnel Desktop version), but problematic with Android Dex Compiler, which tries to merge classes to a dex archive first. However, it builds without errors when you run it on device in debug mode.

Looks like you're trying to build the v1.x branch - it's no longer maintained as a new version written from scratch will be released soon, if you want to contribute or build it, check the [`next`](https://github.com/krlvm/PowerTunnel-Android/tree/next) branch - it builds without any error.
